USE [master]
GO
/****** Object:  Database [MC DONALDS BD]    Script Date: 15/9/2023 08:20:13 ******/
CREATE DATABASE [MC DONALDS BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MC DONALDS BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MC DONALDS BD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MC DONALDS BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MC DONALDS BD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MC DONALDS BD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MC DONALDS BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MC DONALDS BD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET ARITHABORT OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MC DONALDS BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MC DONALDS BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MC DONALDS BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MC DONALDS BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MC DONALDS BD] SET  MULTI_USER 
GO
ALTER DATABASE [MC DONALDS BD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MC DONALDS BD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MC DONALDS BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MC DONALDS BD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MC DONALDS BD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MC DONALDS BD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MC DONALDS BD] SET QUERY_STORE = OFF
GO
USE [MC DONALDS BD]
GO
/****** Object:  Table [dbo].[Acceso]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Acceso](
	[id_empleado] [int] NOT NULL,
	[password] [varchar](200) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Deliverys]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deliverys](
	[nombre] [nchar](10) NULL,
	[destino] [nchar](10) NULL,
	[id_pedido] [nchar](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleados]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleados](
	[id] [int] NOT NULL,
	[nombre_completo] [varchar](100) NOT NULL,
	[dni] [int] NOT NULL,
	[salario] [int] NOT NULL,
	[id_rol] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fila]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fila](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Logistica]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logistica](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[unidad] [int] NOT NULL,
	[id_proveedor] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Menus]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Menus](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[descripcion] [varchar](500) NULL,
	[disponible] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedidos]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedidos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha_pedido] [date] NULL,
	[estado] [bit] NULL,
	[detalle] [varchar](500) NULL,
	[precio] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[descripcion] [varchar](500) NULL,
	[precio] [int] NULL,
	[disponible] [bit] NULL,
	[id_categoria] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos_Menu]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos_Menu](
	[id_menu] [int] NOT NULL,
	[id_producto] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos_Pedido]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos_Pedido](
	[id_pedido] [int] NOT NULL,
	[id_producto] [int] NOT NULL,
	[cantidad] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Proveedores]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proveedores](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[proveedor] [varchar](200) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[rol] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tipo_Entregas]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipo_Entregas](
	[id] [int] NOT NULL,
	[tipo] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ventas]    Script Date: 15/9/2023 08:20:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ventas](
	[venta] [int] NOT NULL,
	[fecha] [date] NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MC DONALDS BD] SET  READ_WRITE 
GO
