USE [master]
GO

/****** Object:  Database [MC DONALDS BD]    Script Date: 1/9/2023 10:13:10 ******/
CREATE DATABASE [MC DONALDS BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MC DONALDS BD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MC DONALDS BD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MC DONALDS BD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MC DONALDS BD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MC DONALDS BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MC DONALDS BD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET ARITHABORT OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MC DONALDS BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MC DONALDS BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MC DONALDS BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MC DONALDS BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MC DONALDS BD] SET  MULTI_USER 
GO

ALTER DATABASE [MC DONALDS BD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MC DONALDS BD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MC DONALDS BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MC DONALDS BD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MC DONALDS BD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MC DONALDS BD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MC DONALDS BD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MC DONALDS BD] SET  READ_WRITE 
GO

